# Generated by Django 5.2.16 on 2026-10-08 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def normalise_paid_status(apps, schema_editor):
    """Earlier migration stored the value as 'PAID'; every other status is lowercase."""
    for model_name in ('Order', 'OrderEvent'):
        apps.get_model('orders', model_name).objects.filter(status='PAID').update(status='paid')


def restore_paid_status(apps, schema_editor):
    for model_name in ('Order', 'OrderEvent'):
        apps.get_model('orders', model_name).objects.filter(status='paid').update(status='PAID')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paystack_reference_alter_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20),
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('endpoint', models.CharField(max_length=200)),
                ('request_hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=12)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='idx_idem_created')],
                'constraints': [models.UniqueConstraint(fields=('user', 'endpoint', 'key'), name='uniq_idem_user_endpoint_key')],
            },
        ),
        migrations.RunPython(normalise_paid_status, restore_paid_status),
    ]
